// Groups many test files into a few shard entrypoints so `flutter test`
// compiles K bundles instead of one kernel per file.
// A root flutter_test_config's testExecutable wraps each shard once, not each
// file: group bodies are sync, so it can't be applied per file.

/// One test file inside a shard. [path] is relative to `test/`, `/`-separated.
final class BundleEntry {
  const BundleEntry(this.path, {this.skip});

  final String path;

  /// Dart expression for `group(skip:)`, translated from a library `@TestOn`.
  final String? skip;
}

final RegExp _testOn = RegExp(r"^@TestOn\((['\x22])(.+?)\1\)", multiLine: true);
// `group(file, main)` throws "Groups may not be async" and fails the shard.
final RegExp _asyncMain = RegExp(
  r'\b(?:Future|FutureOr)<[^>]*>\s+main\s*\(|\bmain\s*\([^)]*\)\s*async\b',
);
final RegExp _otherLibraryAnnotation = RegExp(
  r'^@(Tags|Skip|Timeout|OnPlatform|Retry)\b',
  multiLine: true,
);

const Map<String, String> _platforms = <String, String>{
  'mac-os': 'Platform.isMacOS',
  'linux': 'Platform.isLinux',
  'windows': 'Platform.isWindows',
};

/// `@TestOn('mac-os || linux')` -> `!(Platform.isMacOS || Platform.isLinux)`.
/// Null when the selector uses anything besides OS names and `||`/`&&`/`!`.
String? skipExpressionFor(String selector) {
  final String translated = selector.replaceAllMapped(
    RegExp(r'[a-z][a-z-]*'),
    (Match m) => _platforms[m[0]] ?? '\u0000',
  );
  if (translated.contains('\u0000')) return null;
  return '!($translated)';
}

/// Null when [source] carries a library annotation that `group()` can't
/// express or an async `main`, so the file has to run as its own suite.
BundleEntry? bundleEntryFor(String path, String source) {
  if (_otherLibraryAnnotation.hasMatch(source) || _asyncMain.hasMatch(source)) {
    return null;
  }
  final RegExpMatch? testOn = _testOn.firstMatch(source);
  if (testOn == null) return BundleEntry(path);
  final String? skip = skipExpressionFor(testOn[2]!);
  return skip == null ? null : BundleEntry(path, skip: skip);
}

/// Greedy balance: heaviest file first, always into the lightest shard.
List<List<String>> balanceShards(
  List<String> files,
  int shards,
  int Function(String file) weight,
) {
  final List<String> sorted = <String>[...files]
    ..sort((String a, String b) {
      final int byWeight = weight(b).compareTo(weight(a));
      return byWeight != 0 ? byWeight : a.compareTo(b);
    });
  final int count = shards.clamp(1, files.isEmpty ? 1 : files.length);
  final List<List<String>> result = List<List<String>>.generate(
    count,
    (_) => <String>[],
  );
  final List<int> load = List<int>.filled(count, 0);
  for (final String file in sorted) {
    int lightest = 0;
    for (int i = 1; i < count; i++) {
      if (load[i] < load[lightest]) lightest = i;
    }
    result[lightest].add(file);
    load[lightest] += weight(file);
  }
  return result.where((List<String> s) => s.isNotEmpty).toList();
}

/// Source of a shard living in `test/.bundle/`. [flutter] picks the test
/// package whose `group` the shard calls.
String renderShard(List<BundleEntry> entries, {required bool flutter}) {
  final StringBuffer imports = StringBuffer();
  final StringBuffer groups = StringBuffer();
  for (int i = 0; i < entries.length; i++) {
    final BundleEntry e = entries[i];
    imports.writeln("import '../${e.path}' as t$i;");
    final String skip = e.skip == null ? '' : ', skip: ${e.skip}';
    groups.writeln(
      flutter
          ? "  group('${e.path}', () {\n"
                "    setUpAll(() => _rebaseGoldens(root, '../${e.path}'));\n"
                '    t$i.main();\n'
                '  }$skip);'
          : "  group('${e.path}', t$i.main$skip);",
    );
  }
  final String testLib = flutter
      ? 'package:flutter_test/flutter_test.dart'
      : 'package:test/test.dart';
  return '// GENERATED by elek. Do not edit.\n'
      '// ignore_for_file: directives_ordering, unused_import\n'
      "import 'dart:io';\n\n"
      "import '$testLib';\n\n"
      '$imports\n'
      'void main() {\n'
      '${flutter ? '  final GoldenFileComparator root = goldenFileComparator;\n' : ''}'
      '$groups'
      '}\n'
      '${flutter ? _rebaseGoldensSource : ''}';
}

// Goldens resolve against the suite file, which is the shard; wrappers like
// flame_test's testGolden hide matchesGoldenFile, so rebase for every file.
// A custom comparator from flutter_test_config is left alone.
const String _rebaseGoldensSource = '''

void _rebaseGoldens(GoldenFileComparator root, String file) {
  if (root is LocalFileComparator) {
    goldenFileComparator = LocalFileComparator(root.basedir.resolve(file));
  }
}
''';
